{{ config(materialized='view') }}

select
  ticker,
  symbol,
  exchange,
  null::varchar as company_name,
  ticker as short_name,
  company_type as industry,
  company_type as sector,
  charter_capital,
  extract(year from founded_date)::int as established_year,
  listing_date as listed_date,
  website,
  business_model as description,
  company_type,
  business_model,
  founded_date,
  listing_date,
  number_of_employees,
  par_value,
  listing_price,
  listed_volume,
  outstanding_shares,
  as_of_date,
  ceo_name,
  ceo_position,
  auditor,
  address,
  phone,
  fax,
  email,
  branches,
  history,
  free_float_percentage,
  free_float,
  source,
  company_method,
  snapshot_date,
  fetched_at,
  run_partition,
  source_file
from {{ source('silver', 'company') }}
