{{ config(materialized='view') }}

select
  symbol,
  trading_date,
  exchange,
  ceiling_price::double precision as ceiling_price,
  floor_price::double precision as floor_price,
  reference_price::double precision as reference_price,
  open_price::double precision as open_price,
  high_price::double precision as high_price,
  low_price::double precision as low_price,
  close_price::double precision as close_price,
  average_price::double precision as average_price,
  volume_accumulated,
  total_value::double precision as total_value,
  price_change::double precision as price_change,
  percent_change::double precision as percent_change,
  bid_price_1::double precision as bid_price_1,
  bid_vol_1,
  bid_price_2::double precision as bid_price_2,
  bid_vol_2,
  bid_price_3::double precision as bid_price_3,
  bid_vol_3,
  ask_price_1::double precision as ask_price_1,
  ask_vol_1,
  ask_price_2::double precision as ask_price_2,
  ask_vol_2,
  ask_price_3::double precision as ask_price_3,
  ask_vol_3,
  foreign_buy_volume,
  foreign_sell_volume,
  foreign_room,
  source,
  snapshot_at,
  is_suspicious,
  run_partition,
  source_file
from {{ source('silver', 'price_board') }}
