name: stock_pipeline
version: "1.0.0"
config-version: 2

profile: stock_pipeline

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  stock_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
