stock_pipeline:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PG_HOST', 'localhost') }}"
      port: "{{ env_var('PG_PORT', '55432') | as_number }}"
      user: stock
      password: stock
      dbname: stock_pipeline
      schema: gold
      threads: 4
